services:
  django:
    build:
      context: ./DjangoProject1
      dockerfile: Dockerfile
    command: /app/.venv/bin/python manage.py runserver 0.0.0.0:8000
    
    ports:
      - "8000:8000"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile

    ports:
      - "5000:5000"