services:
  django:
    build:
      context: ./DjangoProject1
      dockerfile: Dockerfile
      
    ports:
      - "8000:8000"
    command: sh -c "echo 'Django running on http://0.0.0.0:8000'" #simplement per mostrar la url de Django al iniciar el contenedor si algo falla podem borrar

  api:
    build:
      context: ./api
      dockerfile: Dockerfile

    ports:
      - "5000:5000"