# Generated by Django 4.2.11 on 2026-04-13 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mail', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.URLField()),
                ('forwards', models.IntegerField()),
                ('midfielders', models.IntegerField()),
                ('defenders', models.IntegerField()),
                ('goalKeeper', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('name', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=200)),
                ('game', models.CharField(max_length=200)),
                ('archetype', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('element', models.CharField(max_length=200)),
                ('power', models.IntegerField()),
                ('control', models.IntegerField()),
                ('technique', models.IntegerField()),
                ('physical', models.IntegerField()),
                ('agility', models.IntegerField()),
                ('age_Group', models.CharField(max_length=200)),
                ('school_Year', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.teams')),
            ],
        ),
        migrations.CreateModel(
            name='Futdraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.lineup')),
                ('players', models.ManyToManyField(related_name='draft_players', to='myapp.players')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.appuser')),
            ],
        ),
    ]
