# Generated by Django 6.0.3 on 2026-04-14 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.URLField()),
                ('forwards', models.IntegerField()),
                ('midfielders', models.IntegerField()),
                ('defenders', models.IntegerField()),
                ('goalKeeper', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('name', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=200)),
                ('game', models.CharField(max_length=200)),
                ('archetype', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('element', models.CharField(max_length=200)),
                ('power', models.IntegerField()),
                ('control', models.IntegerField()),
                ('technique', models.IntegerField()),
                ('physical', models.IntegerField()),
                ('agility', models.IntegerField()),
                ('intelligence', models.IntegerField(default=0)),
                ('total', models.IntegerField()),
                ('age_Group', models.CharField(max_length=200)),
                ('school_Year', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Futdraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.lineup')),
                ('players', models.ManyToManyField(related_name='draft_players', to='myapp.players')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='players',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.teams'),
        ),
    ]
