# Generated by Django 6.0.3 on 2026-04-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_futdraft_player_order_alter_futdraft_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='pressure',
            field=models.IntegerField(default=0),
        ),
    ]
