# Generated by Django 6.0.3 on 2026-04-19 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_players_pressure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='age_Group',
            new_name='age_group',
        ),
        migrations.RenameField(
            model_name='players',
            old_name='school_Year',
            new_name='school_year',
        ),
    ]
